### ISSUE TITLE
it can not audio

### ISSUE THREAD

**Issue by HeywoodKing** [andrewkirillov/AForge.NET#20]
I think the question with audio,Urgently needed to solve

**Comment by cesarsouza** [comment]
Hello there,

Please, may I ask what do you need to do with audio? Do you need to record it? Alone or inside a video?

You might have the possibility of working with audio with the [Accord.NET project](https://github.com/accord-net/framework), that is trying to give continuation to the excellent APIs that originated in AForge. It supports audio recording and playback, and can also capture video with audio using FFMPEG.

Regards,
Cesar

**Comment by andrewkirillov** [comment]
Audio was never on the list of features for AForge.NET Framework.
