### ISSUE TITLE
Fix for Directshow Snapshot Capability Detection

### ISSUE THREAD

**Issue by simonbuehler** [andrewkirillov/AForge.NET#26]
HI,

i always got "no snapshots supported" for my Logitech c920 Webcam. It does not support _external_ trigger but Software trigger, so the condition should be less restrictive:

in Directshow.VideoCaptureDevice

line 1100 the change should be
``isSapshotSupported = ((caps & VideoControlFlags.ExternalTriggerEnable) != 0 );``

to

``isSapshotSupported = ((caps & VideoControlFlags.ExternalTriggerEnable) != 0 || (caps & VideoControlFlags.Trigger) != 0);``

and boom - it works!

**Comment by andrewkirillov** [comment]
Fixed.
