### ISSUE TITLE
Excessive occupancy of CPU

### ISSUE THREAD

**Issue by loyalto** [andrewkirillov/AForge.NET#28]
My computer processor is i5, and when I connect the 8 million pixel camera, CPU reaches 99%, how do I solve it?

**Comment by andrewkirillov** [comment]
If you say it happens when you connect the camera, then the quickest solution would be to simply disconnect it.

Alternative solution would be to take some profiling tools and see which part of the code is the causes performance issues.

**Comment by kzgrey** [comment]
Is this project still being actively maintained?  If not, is anyone aware of an alternative that integrates with .NET well?

**Comment by kzgrey** [comment]
Awesome, thanks!
