### ISSUE TITLE
Redundant check on many PixelFormats

### ISSUE THREAD

**Issue by hzawary** [andrewkirillov/AForge.NET#3]
Dear Andrew,

There is no problem, but I just want reporting a redundant check on some methods, e.g. on abstract BlobCounterBase class:
__________________________________________________________________________
public Blob[] GetObjects( UnmanagedImage image, bool extractInOriginalSize ) 
665         { 
666             // check if objects map was collected 
667             if ( objectLabels == null ) 
668                 throw new ApplicationException( "Image should be processed before to collect objects map." ); 
669 
 
670             if ( 
671                 ( image.PixelFormat != PixelFormat.Format24bppRgb ) && 
672                 ( image.PixelFormat != PixelFormat.Format8bppIndexed ) && 
673                 ( image.PixelFormat != PixelFormat.Format32bppRgb ) && 
674                 ( image.PixelFormat != PixelFormat.Format32bppArgb ) && 
675                 ( image.PixelFormat != PixelFormat.Format32bppRgb ) && 
676                 ( image.PixelFormat != PixelFormat.Format32bppPArgb ) 
677                 ) 
678                 throw new UnsupportedImageFormatException( "Unsupported pixel format of the provided image." ); 
__________________________________________________________________________
On 673 and 675 lines.

Best the wishes,
Hashem.

**Comment by andrewkirillov** [comment]
Seem to be a copy paste typo :( Well, if compiler is smart enough it will take care of it. But to make it cleaner it could be fixed.
