### ISSUE TITLE
Frame Size and Video Resolution

### ISSUE THREAD

**Issue by jis1218** [andrewkirillov/AForge.NET#33]
I am using 4K webcam and trying to capture 4K image but make it stream on 1080p monitor.

By using your sample 'snap shot maker' on http://www.aforgenet.com/framework/samples/video.html,

4K image is shown in smaller box.

By using the VideoSourcePlayer.cs, however, 4K image is shown in the 3840x2160 itself, and I can see only edge of the image.

`_videoSource.VideoResolution = videoCapabilities[comboBox1.SelectedIndex];
videoSourcePlayer1.VideoSource = _videoSource;
 videoSourcePlayer1.Start();
`

What kind of process I have to do? Do I need to convert bitmap size? Or changing frame size will work?

Thank you!

**Comment by andrewkirillov** [comment]
>> What kind of process I have to do? Do I need to convert bitmap size? Or changing frame size will work?
Don't know. It depends on what you want. You can resize image itself, if this is what you need. If you use VideoSourcePlayer, you can try its AutoSizeControl property. See docs:
http://www.aforgenet.com/framework/docs/html/f172b9cf-22f7-28ce-20c1-3c30674c5475.htm

If you use .NET's PictureBox, then use its SizeMode property:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.picturebox.sizemode?view=netframework-4.7.2#System_Windows_Forms_PictureBox_SizeMode
