### ISSUE TITLE
Aforgenet.com is down

### ISSUE THREAD

**Issue by joonalaine** [andrewkirillov/AForge.NET#55]
Go see for yourself. This is very unfortunate as it's the only source of API docs.

**Comment by joonalaine** [comment]
Live now, good job!

**Comment by dmwest81** [comment]
Aforgenet.com is down again. I'm looking for the API docs too.

**Comment by andrewkirillov** [comment]
Back on-line, Don't know how long it is going to stay - the service provider seems terrible this days.
