### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by spoiledtechie** [andrewkirillov/AForge.NET#7]
Andrew,

I am trying to compile the project my self.  Needing to recompile Video.FFMPEG

I already installed 2008, 2010 and still missing AForge references.

I then included the project in the BuildAll solution and that took care of the references, but now receiving the following

Error	6	error C1859: 'Release\AForge.Video.FFMPEG.pch' unexpected precompiled header error, simply rerunning the compiler might fix this problem	C:\Development\AForge.NET\Sources\Video.FFMPEG\AssemblyInfo.cpp	1	1	Video.FFMPEG

Any thoughts?

I would love it if you were able to create a small write up to get started compiling?

**Comment by andrewkirillov** [comment]
Hello,

I did not have this issue. However I did not build AForge.Video.FFMPEG on Windows 7 recently, so could miss it. My build machine still was Windows Vista.

Anyway, this seem to be a known issue and well described:
http://blogs.msdn.com/b/vcblog/archive/2009/11/12/visual-c-precompiled-header-errors-on-windows-7.aspx
https://support.microsoft.com/en-us/kb/976656

Regards,
Andrew
